apiVersion: v1
kind: Pod
metadata:
  name: 01-sample
  labels:
    name: sample
spec:
  containers:
  - name: httpd
    image: httpd
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
