- name: Install Web and Application for Student Project 
  hosts: localhost 
  become: yes
  tasks:
    - name: Include Web Service 
      include_role: 
        name: webservice
      when: ansible_os_family == "RedHat"
      
    - name: Include App Service 
      include_role: 
        name: appservice
      when: ansible_os_family == "RedHat"

