--- 
apiVersion: v1
kind: Namespace
metadata:
  name:  webservice
...
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web
  namespace: webservice
  labels:
    app: httpd
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: httpd
        image: rkalluru/b36-web:v2
        env:
          - name: UI_ENDPOINT 
            valueFrom:
              configMapKeyRef:
                key: UI_ENDPOINT
                name: app-endpoint-config
          - name: API_ENDPOINT 
            valueFrom:
              configMapKeyRef:
                key: API_ENDPOINT
                name: app-endpoint-config
...

--- 
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: webservice
spec:
  type: LoadBalancer
  selector:
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
...

---
apiVersion: v1
data:
  UI_ENDPOINT: app-service.appui.svc.cluster.local
  API_ENDPOINT: api-service.appapi.svc.cluster.local
kind: ConfigMap
metadata:
  name: app-endpoint-config
  namespace: webservice
... 

