--- 
apiVersion: v1
kind: Namespace
metadata:
  name:  appapi
...
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app
  namespace: appapi
  labels:
    app: java
    tier: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: middleware
  template:
    metadata:
      labels:
        tier: middleware
    spec:
      containers:
      - name: api
        image: rkalluru/b36-app-api:v1
        env:
          - name: RDS_USER
            valueFrom:
              secretKeyRef:
                key: DBUSER 
                name: db-secret
          - name: RDS_PASS
            valueFrom:
              secretKeyRef:
                key: DBPASS 
                name: db-secret
          - name: RDS_ENDPOINT 
            valueFrom:
              configMapKeyRef:
                key: DBENDPOINT
                name: db-config
...

--- 
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: appapi
spec:
  selector:
    tier: middleware
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
...

---
apiVersion: v1
data:
  DBENDPOINT: mariadb-service.database.svc.cluster.local
  DBNAME: studentapp 
kind: ConfigMap
metadata:
  name: db-config
  namespace: appapi
... 

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: appapi
type: Opaque
data:
  DBUSER: c3R1ZGVudA==
  DBPASS: c3R1ZGVudEAx
... 
