apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rc
  labels:
    app: webservice
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: httpd
        image: httpd 
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
          - containerPort: 80
