apiVersion: v1
kind: Pod
metadata:
  name: env-demo
  labels:
    app: myapp
spec:
  containers:
  - name: centos
    image: centos
    command: ['sleep', '100000']
    env:
    - name: COURSE_NAME
      value: DEVOPS