- name: Find and remove files 
  hosts: TEST 
  become: yes
  tasks:
    - name: find the files and directories 
      find:
        paths: /tmp/demo
        file_type: any 
        patterns: 'student*'
      register: out 

    - name: Remove files and directory 
      file:
        path: "{{item.path}}"
        state: absent
      loop: "{{out.files}}"