- name: Loop control 
  hosts: TEST 
  tasks:
    - name: Demo 
      debug:
       msg: "{{item.name}}"
      loop:
       - name: vi
         state: installed
         os: redhat
         limits:
           cpu: 1
           mem: 1gb
         
       - name: gcc
       - name: zip
      loop_control: 
        label: "{{item.name}}"