- name: Demo on filters 
  hosts: TEST 
  vars:
    URL: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.38/bin/apache-tomcat-8.5.38.tar.gz
    FILE: "{{ URL.split('/') | last}}"
    DIR: "{{FILE | regex_replace('.tar.gz') }}"
  tasks: 
    - name: FILE 
      debug:
        msg: "FILE = {{FILE}}, DIR = {{DIR}}"