---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  COURSE: REVWT1BT
  TIME: N2Ft
... 


--- 
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    app: myapp
spec:
  containers:
  - name: centos
    image: centos
    command: ['sleep', '100000']
    env:
    - name: COURSE_NAME
      valueFrom:
        secretKeyRef:
          key: COURSE
          name: mysecret
    - name: COURSE_TIME
      valueFrom:
        secretKeyRef:
          key: TIME
          name: mysecret
...