---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
... 

--- 
apiVersion: v1
kind: Pod
metadata:
  name: pvc-access
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: demo1
...