---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: rkalluru/b36-httpd:v1
        ports:
        - containerPort: 80
...

---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  type: LoadBalancer
  selector:
    app: httpd
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
...