- include: pre-requisites.yml

- name: Add student user 
  user:
    name: "{{APP_USER}}"
    state: present 

- name: DOwnload and extract tomcat.
  unarchive:
    src: "{{TOMCAT_URL}}"
    dest: /home/student
    remote_src: yes
  become_user: "{{APP_USER}}"

- name: Find old war file 
  find:
    paths: "{{TOMCAT_DIR}}/webapps"
    file_type: any 
    patterns: 'student*'
  register: out  

- name: Remove old war files if any 
  file:
    path: "{{item.path}}"
    state: absent
  loop: "{{out.files}}"

- name: Download war file 
  get_url:
    url: "{{WAR_URL}}"
    dest: "{{TOMCAT_DIR}}/webapps/student.war"
  become_user: "{{APP_USER}}"

- name: Download the JDBC jar file 
  get_url:
    url: "{{JDBC_JAR_URL}}"
    dest: "{{TOMCAT_DIR}}/lib/mysql-jdbc.jar"
  become_user: "{{APP_USER}}"

- name: Update JDBC Connection 
  template:
    src: context.xml.j2
    dest: "{{TOMCAT_DIR}}/conf/context.xml"
  become_user: "{{APP_USER}}"
  
- name: Setup tomcat init script 
  get_url: 
    url:  "{{TOMCAT_INIT_URL}}"
    dest: /etc/init.d/tomcat
    mode: 0755 

- name: Reload systemctld 
  shell: systemctl daemon-reload

- name: Restart tomcat service 
  service:
    name: tomcat 
    state: restarted
    enabled: yes

- name: Remove API Directory 
  file:
    path: /home/student/api
    state: absent

- name: Create API Directory 
  file:
    path: /home/student/api
    state: directory
  become_user: "{{APP_USER}}"

- name: Download war file 
  get_url:
    url: "{{API_URL}}"
    dest: /home/student/api/studentapi.war 
  become_user: "{{APP_USER}}"

- name: Setup DB Paramaters
  blockinfile:
    path: /home/{{APP_USER}}/.bashrc
    block: |
      export RDS_ENDPOINT={{DBHOST}}
      export RDS_USER={{DBUSER}}
      export RDS_PASS={{DBPASS}}

- name: Copy Api Init script 
  copy:
    src: studentapi-init 
    dest: /etc/init.d/studentapi 
    mode: 0755 

- name: Systemctl daemon reolaod 
  shell: systemctl daemon-reload 

- name: Start Student API Service 
  service:
    name: studentapi 
    state: started 
    enabled: yes 
